name: Build Zephyr applications
run-name: Build apps for ${{ inputs.repo || github.repository }}

on:
  # When a remote repo call this reusable workflow, these inputs may or must be set
  workflow_call:
    inputs:
      sdk_version:
        description: "Zephyr SDK version"
        required: false
        default: "1.0.1"
        type: string
      applications_file:
        type: string
        required: false
        default: ci/applications_for_build.yaml        
      repo:
        description: 'Repository to be used for checkout'
        required: false
        type: string
    secrets:
      personal_access_token:
        required: true
          
  # When manually starting the workflow, these inputs are available
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "Zephyr SDK version"
        required: false
        default: "1.0.1"
        type: string
      applications_file:
        type: string
        required: false
        default: ci/applications_for_build.yaml
      repo:
        description: 'Private repository to be used for checkout (format: URL)'
        required: false
        type: string

jobs:              
  build:
    name: Build ${{ matrix.application }} for ${{ matrix.board }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
        
    steps:
      # Clone the local repository (if applicable)
      - name: Checkout
        if: "${{ inputs.repo == '' }}"
        uses: actions/checkout@v7
        with:
          repository: ${{ inputs.repo || github.repository }}

      # Clone the remote repository (if applicable)
      - name: Clone remote repository
        if: "${{ inputs.repo != '' }}"
        shell: bash
        env:
          ACCESS_TOKEN: ${{ secrets.ADVEMBSOF_2025_2026 }}
        run: |
          REPO_URL="${{ inputs.repo }}"
          REPO_PATH=${REPO_URL#https://github.com/}
          git clone "https://x-access-token:${ACCESS_TOKEN}@github.com/${REPO_PATH}" .
          # Switch to target branch if provided
          if [ -n "${{ github.event.inputs.branch }}" ]; then
            echo "Switching to branch: ${{ github.event.inputs.branch }}"
            git fetch origin ${{ github.event.inputs.branch }}
            git checkout ${{ github.event.inputs.branch }}
          else
            echo "Using default branch"
          fi

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v6.3.0
        with:
          python-version: '3.13'

      # In a ubuntu image, setup zephyr environment
      - name: Setup Zephyr
        uses: AdvEmbSof/setup-zephyr-action@v1
        timeout-minutes: 5
        with:
          sdk_version: ${{ github.event.inputs.sdk_version || '1.0.1' }}
          path_west_workspace: ${{ github.workspace }}
          path_west_manifest: ${{ github.workspace }}/manifest-repo/

      # Build the matrix to be used for west commands
      - name: Install PyYAML
        run: pip install pyyaml

      - name: Build matrix
        id: build-matrix
        shell: python
        env:
          APPS: ${{ inputs.applications_file }}
          
        run: |
          import json
          import os
          import yaml
          
          with open(os.environ["APPS"], "r") as f:
              config = yaml.safe_load(f)
          
          matrix = []

          for app in apps:
              for board in app["boards"]:
                  for spec in app["specs"]:
                      matrix.append({
                          "app": app["app"],
                          "board": board,
                          "spec": spec,
                      })

          echo "matrix={json.dumps(matrix)}" >> "$GITHUB_OUTPUT" 
          
      # Build the application using west command
      - name: Build ${{ steps.build-matrix.outputs.matrix.app }}
        run: |
          python deps/zpp_lib/scripts/build.py \
            --app "${{ steps.build-matrix.outputs.matrix.app }}" \
            --specs "${{ steps.build-matrix.outputs.matrix.specs }}" \
            --board "${{ matrix.board }}"
          
