name: Build Zephyr applications
run-name: Build apps for ${{ inputs.repo || github.repository }}

on:
  # When a remote repo call this reusable workflow, these inputs may or must be set
  workflow_call:
    inputs:
      sdk_version:
        description: "Zephyr SDK version"
        required: false
        default: "0.17.0"
        type: string
      boards:
        description: "List of boards (JSON array)"
        required: true
        default: '["nrf5340dk/nrf5340/cpuapp","qemu_x86"]'
        type: string
      applications:
        description: "List of applications (JSON array)"
        required: true
        default: '["bike_computer","blinky","sensor-bme280"]'
        type: string
      repo:
        description: 'Repository to be used for checkout'
        required: false
        type: string
    secrets:
      personal_access_token:
        required: true
          
  # When manually starting the workflow, these inputs are available
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "Zephyr SDK version"
        required: false
        default: "0.17.0"
        type: string
      boards:
        description: "List of boards (JSON array)"
        required: true
        default: '["nrf5340dk/nrf5340/cpuapp","qemu_x86"]'
        type: string
      applications:
        description: "List of applications (JSON array)"
        required: true
        default: '["bike_computer","blinky","sensor-bme280"]'
        type: string
      repo:
        description: 'Private repository to be used for checkout (format: URL)'
        required: false
        type: string

jobs:
  build:
    name: Build ${{ matrix.application }} for ${{ matrix.board }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: ${{ fromJSON(inputs.boards) }}
        application: ${{ fromJSON(inputs.applications) }}

    steps:
      # Clone the local repository (if applicable)
      - name: Checkout
        if: "${{ inputs.repo == '' }}"
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo || github.repository }}

      # Clone the remote repository (if applicable)
      - name: Clone remote repository
        if: "${{ inputs.repo != '' }}"
        shell: bash
        env:
          ACCESS_TOKEN: ${{ secrets.ADVEMBSOF_2025_2026 }}
        run: |
          REPO_URL="${{ inputs.repo }}"
          REPO_PATH=${REPO_URL#https://github.com/}
          git clone "https://x-access-token:${ACCESS_TOKEN}@github.com/${REPO_PATH}" .
          # Switch to target branch if provided
          if [ -n "${{ github.event.inputs.branch }}" ]; then
            echo "Switching to branch: ${{ github.event.inputs.branch }}"
            git fetch origin ${{ github.event.inputs.branch }}
            git checkout ${{ github.event.inputs.branch }}
          else
            echo "Using default branch"
          fi

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # In a ubuntu image, setup zephyr environment
      - name: Setup Zephyr
        uses: AdvEmbSof/setup-zephyr-action@v1
        timeout-minutes: 5
        with:
          sdk_version: ${{ github.event.inputs.sdk_version || '0.17.0' }}
          path_west_workspace: ${{ github.workspace }}
          path_west_manifest: ${{ github.workspace }}/manifest-repo/

      # Build the application using west command
      - name: Build ${{ matrix.application }}
        run: |
          if [ "${{ matrix.board }}" = "nrf5340dk/nrf5340/cpuapp" ]; then
            west build -p -b ${{ matrix.board }} ${{ matrix.application }} --shield adafruit_2_8_tft_touch_v2
          else
            west build -p -b ${{ matrix.board }} ${{ matrix.application }}
          fi
