name: Test Zephyr applications
run-name: Twister Tests for ${{ inputs.repo || github.repository }}

# Given that setting up Zephyr, we do not distribute jobs using a matrix,
# but we rather setup Zephyr once and build applications sequentially using the build_from_config script

on:
  # When a remote repo call this reusable workflow
  workflow_call:
    inputs:
      sdk_version:
        description: "Zephyr SDK version"
        required: false
        default: "1.0.1"
        type: string
      configuration_file:
        type: string
        required: false
        default: ci/applications_for_test.yaml
    secrets:
      personal_access_token:
        required: true
        
  # When manually starting the workflows, these inputs are available
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "Zephyr SDK version"
        required: false
        default: "1.0.1"
        type: string
      configuration_file:
        type: string
        required: false
        default: ci/applications_for_test.yaml
      repo:
        description: 'Public repository to be used for checkout (format: owner/repo not URL)'
        required: false
        type: string
        
permissions:
  checks: write
  pull-requests: write
  contents: read
  
jobs:
  tests:
    runs-on: ubuntu-latest
       
    steps:
      # Clone the local repository (if applicable)
      - name: Checkout
        if: "${{ inputs.repo == '' }}"
        uses: actions/checkout@v7
        with:
          repository: ${{ inputs.repo || github.repository }}

      # Clone the remote repository (if applicable)
      - name: Clone remote repository
        if: "${{ inputs.repo != '' }}"
        shell: bash
        env:
          ACCESS_TOKEN: ${{ secrets.ADVEMBSOF_2025_2026 }}
        run: |
          REPO_URL="${{ inputs.repo }}"
          REPO_PATH=${REPO_URL#https://github.com/}
          git clone "https://x-access-token:${ACCESS_TOKEN}@github.com/${REPO_PATH}" .
          # Switch to target branch if provided
          if [ -n "${{ github.event.inputs.branch }}" ]; then
            echo "Switching to branch: ${{ github.event.inputs.branch }}"
            git fetch origin ${{ github.event.inputs.branch }}
            git checkout ${{ github.event.inputs.branch }}
          else
            echo "Using default branch"
          fi
          
      # In a ubuntu image, setup zephyr environment
      - name: Setup Zephyr
        uses: AdvEmbSof/setup-zephyr-action@v2
        timeout-minutes: 5
        with:
          sdk_version: ${{ inputs.sdk_version }}
          path_west_workspace: ${{ github.workspace }}
          path_west_manifest: ${{ github.workspace }}/manifest-repo/

      # Run the tests using the twister.py script
      - name: Run twister from config
        id: twister_cmd
        run: |
          python deps/zpp_lib/scripts/twister_from_config.py --config ${{ inputs.configuration_file }} --board qemu_x86
            
      # Sets variables used for naming the artifact
      - name: Set variables
        if: success() || failure()
        id: vars
        run: |
          echo "run_id=${{ github.run_id}}" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Make available test results in artifacts
      - name: Archive test results
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: aes_${{ steps.vars.outputs.run_id }}_${{ steps.vars.outputs.sha_short }}
          path: |
            twister-out/testplan.json
            twister-out/twister_report.xml
            twister-out/twister_suite_report.xml
            twister-out/twister.json
            twister-out/testplan.json
            twister-out/**/*.log

      # Plot Test results in the caller UI Github
      - name: Publish test results
        if: success() || failure()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: twister-out/twister_suite_report.xml
          check_name: "${{ matrix.test }} tests summary"
          check_run_annotations: 'all tests'
          comment_mode: always
          job_summary: true          
